#!/bin/zsh

# Short cut for querying the smart contract
# chomd +x
# ./execute $CONTRACT $ACTION 

echo $argv[1] "$argv[2]" $argv[3] $argv[4] $argv[5] $argv[6] $argv[7] $argv[8] $argv[9] $argv[10] $argv[11] $argv[12]
wasmd tx wasm execute $argv[1] "$argv[2]" --amount 100umlg --from wallet $argv[3] $argv[4] $argv[5] $argv[6] $argv[7] $argv[8] $argv[9] $argv[10] $argv[11] $argv[12]