#!/bin/zsh

# Short cut for querying the smart contract
# chomd +x
# ./execute $CONTRACT $ACTION 

echo $argv[1] "$argv[2]" $argv[3] $argv[4]
wasmd tx wasm execute $argv[1] "$argv[2]" --amount 100umlg --from alice $argv[3] $argv[4]